### ISSUE TITLE
pdf format response with pdf link

### ISSUE THREAD

**Issue by oltdaniel** [Dragonsight91/DS-API#5]
**Is your feature request related to a problem? Please describe.**
I am really frustrated to open the console and parse the website to load all links and put them into an textfile to then download it via a bash script an `wget`.

**Describe the solution you'd like**
Just a small switch for the file formats, an if would be enough and just reply with the url you are being redirected to. Important: Don't load the full document... only the url.

**Describe alternatives you've considered**
None. THIS IS THE ONLY WAY

**Additional context**
As we expect this kind of page for LA next semester, it would be nice to have an endpoint that works to crawl that piece of shit site.

BTW: rename the endpoint `/exircise` to `/exercise`. Just a typo.

**Comment by Dragonsight91** [comment]
Format switch does exist, might be undocumented, i'll see what i can do about the file transfer, might behave weirdly because it responds to a POST request with the document.

I'll work on this idea first, should be a simple fix.

**Comment by Dragonsight91** [comment]
You should now get a direct `application/pdf` response in `/exercises` with the format set to `PDF`. first time might take a second, because of caching. Documentation will be added soon
