### ISSUE TITLE
get a list of all exercises in an array

### ISSUE THREAD

**Issue by oltdaniel** [Dragonsight91/DS-API#6]
**Is your feature request related to a problem? Please describe.**
Would be nice to request all available exercise papers, maybe with each content in the requested format. Just some bulk request.

**Describe the solution you'd like**
A new endpoint handling bulk requests.

**Describe alternatives you've considered**
None. This is the only way as always.

**Additional context**
The part of containing each content, is optional.

**Comment by Dragonsight91** [comment]
`/exercises` will now send an array with filenames and download links see PR #10 and README for more info.
